services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sbangular
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
  api:
    build: 
      context: ./sb-angular-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./sb-angular-backend/src:/app/src
      - ./sb-angular-backend/build:/app/build
    depends_on:
      - postgres
volumes:
  postgres_data: